[package]
name = "pulse-pet"
version = "0.1.0"
description = "PulsePet desktop pet"
authors = ["you"]
edition = "2021"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and not conflict with the bin name
# (Windows-only issue, see https://github.com/rust-lang/cargo/issues/8519).
name = "pulse_pet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-single-instance = "2"
rusqlite = { version = "0.40", features = ["bundled"] }
